### ISSUE TITLE
Create DB user and product

### ISSUE THREAD

**Issue by GXcode95** [GXcode95/LesChatons#6]
Explication
Tous nos produits à vendre seront dans une belle table qui stockera les produits. Cette table va s'appeler Item, et aura comme attributs :

un title, string
une description, text
un price, decimal (tu peux faire une petite recherche Google sur l'intérêt du decimal pour un prix)
une image_url, string

┆Issue is synchronized with this [Trello card](https://trello.com/c/wAF3AwOe) by [Unito](https://www.unito.io)

**Comment by antcrn** [comment]
Add Model User with devise
Add Model Item
